#!/bin/bash
docker stop masterdb
docker stop slavedb
docker rm masterdb
docker rm slavedb
rm -r /opt/Docker/masterdb/data
rm -r /opt/Docker/slavedb/data
mkdir -p /opt/Docker/masterdb/data /opt/Docker/slavedb/data
cp config-file.cnf /opt/Docker/masterdb/cnf/config-file.cnf
cp config-fileSlave.cnf /opt/Docker/slavedb/cnf/config-file.cnf
docker run --name masterdb -v /opt/Docker/masterdb/cnf:/etc/mysql/conf.d -v /opt/Docker/masterdb/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=mysecretpass -d percona:5.6
docker exec -ti masterdb 'mysql' -uroot -pmysecretpass -vvv -e"GRANT REPLICATION SLAVE ON *.* TO repl@'%' IDENTIFIED BY 'slavepass';" 
docker exec -ti masterdb 'mysql' -uroot -pmysecretpass -e"SHOW MASTER STATUS;"
docker run --name slavedb -d -v /opt/Docker/slavedb/cnf:/etc/mysql/conf.d -v /opt/Docker/slavedb/data:/var/lib/mysql --link masterdb:mysql -e MYSQL_ROOT_PASSWORD=mysecretpass -d percona:5.6
docker exec -ti slavedb 'mysql' -uroot -pmysecretpass -e'change master to master_host="mysql",master_user="repl",master_password="slavepass",master_log_file="mysqld-bin.000004",master_log_pos=310;"' -vvv
docker exec -ti slavedb 'mysql' -uroot -pmysecretpass -e"START SLAVE;" -vvv
docker exec -ti slavedb 'mysql' -uroot -pmysecretpass -e"SHOW SLAVE STATUS;" -vvv
docker exec -ti masterdb 'mysql' -uroot -pmysecretpass -e"GRANT ALL ON db.* TO 'root'@'%' IDENTIFIED BY 'rootrootR$1' WITH GRANT OPTION;" -vvv
docker exec -ti slavedb 'mysql' -uroot -pmysecretpass -e"GRANT ALL ON db.* TO 'root'@'%' IDENTIFIED BY 'rootrootR$1' WITH GRANT OPTION;" -vvv
docker exec -ti masterdb 'mysql' -uroot -pmysecretpass > ddlLog.sql
docker exec -ti slavedb 'mysql' -uroot -pmysecretpass > ddlLog.sql

