
CREATE SCHEMA IF NOT EXISTS ESHOP DEFAULT CHARACTER SET latin1 ;
USE ESHOP ;

CREATE TABLE IF NOT EXISTS ESHOP.ADDRESS (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  COUNTRY VARCHAR(80) NULL DEFAULT NULL,
  CITY VARCHAR(45) NULL DEFAULT NULL,
  STREET VARCHAR(45) NULL DEFAULT NULL,
  BUILDING_NO VARCHAR(45) NULL DEFAULT NULL,
  FLAT_NO VARCHAR(45) NULL DEFAULT NULL,
  POST_CODE VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS ESHOP.CUSTOMER (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(40) NULL DEFAULT NULL,
  SURNAME VARCHAR(80) NULL DEFAULT NULL,
  ID_ADDRESS_INVOICE INT(11) NULL DEFAULT NULL,
  EMAIL VARCHAR(100) NULL DEFAULT NULL,
  CUSTOMER_TYPE VARCHAR(45) NULL DEFAULT NULL,
  PESEL VARCHAR(9) NULL DEFAULT NULL,
  ID_ADDRESS_DELIVERY INT(11) NULL DEFAULT NULL,
  COMPANY_NAME VARCHAR(100) NULL DEFAULT NULL,
  PHONE_NUMBER VARCHAR(20) NULL DEFAULT NULL,
  NIP VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX FK_CUST_DELI_idx (ID_ADDRESS_DELIVERY ASC),
  INDEX FK_CUST_INV_idx (ID_ADDRESS_INVOICE ASC),
  CONSTRAINT FK_CUST_DELI
    FOREIGN KEY (ID_ADDRESS_DELIVERY)
    REFERENCES ESHOP.ADDRESS (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_CUST_INV
    FOREIGN KEY (ID_ADDRESS_INVOICE)
    REFERENCES ESHOP.ADDRESS (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS ESHOP.DELIVERY (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  DELIVERY_TYPE VARCHAR(45) NULL DEFAULT NULL,
  DESCRIPTION VARCHAR(45) NULL DEFAULT NULL,
  DELIVERY_PRICE DECIMAL(10,0) NULL DEFAULT NULL,
  DELIVERY_DAYS INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS ESHOP.DISCOUNT_CODE (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  PERCENT_DISCOUNT DECIMAL(10,0) NULL DEFAULT NULL,
  DATE_FROM DATE NULL DEFAULT NULL,
  DATE_TO DATE NULL DEFAULT NULL,
  CODE VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS ESHOP.ORDER (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  CREATE_DATE DATETIME NULL DEFAULT NULL,
  CUSTOMER_ID INT(11) NOT NULL,
  ORDER_TYPE VARCHAR(45) NULL DEFAULT 'NORMAL',
  IS_PAID VARCHAR(1) NULL DEFAULT 'N',
  PAYMENT_TYPE VARCHAR(45) NULL DEFAULT NULL,
  MESSAGE VARCHAR(100) NULL DEFAULT NULL,
  STATUS VARCHAR(45) NULL DEFAULT NULL,
  ORDER_SID VARCHAR(45) NULL DEFAULT NULL,
  DISCOUNT DECIMAL(10,0) NULL DEFAULT NULL,
  DELIVERY_TYPE VARCHAR(45) NULL DEFAULT NULL,
  TOTAL_PRICE DECIMAL(10,0) NULL DEFAULT NULL,
  PRODUCT_PRICE DECIMAL(10,0) NULL DEFAULT NULL,
  DELIVERY_PRICE DECIMAL(10,0) NULL DEFAULT NULL,
  INVOICE_NO VARCHAR(45) NULL DEFAULT NULL,
  INVOICE_DATE VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (ID),
  INDEX FK_ORD_CUST_idx (CUSTOMER_ID ASC),
  CONSTRAINT FK_ORD_CUST
    FOREIGN KEY (CUSTOMER_ID)
    REFERENCES ESHOP.CUSTOMER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE TABLE IF NOT EXISTS ESHOP.PRODUCT_CATEGORY (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NULL DEFAULT NULL,
  DESCRIPTION VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (ID));

CREATE TABLE IF NOT EXISTS ESHOP.PRODUCT (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  PRODUCT_TYPE VARCHAR(45) NULL DEFAULT NULL,
  PRODUCT_CATEGORY_ID INT(11) NOT NULL,
  DESCRIPTION VARCHAR(45) NULL DEFAULT NULL,
  PRODUCT_NO VARCHAR(45) NULL DEFAULT NULL,
  PRODUCT_PRICE VARCHAR(45) NULL DEFAULT NULL,
  IS_IN_SPECIAL_OFFERS VARCHAR(45) NULL DEFAULT 'N',
  PRIMARY KEY (ID),
  INDEX fk_PRODUCT_1_idx (PRODUCT_CATEGORY_ID ASC),
  CONSTRAINT fk_PRODUCT_1
    FOREIGN KEY (PRODUCT_CATEGORY_ID)
    REFERENCES ESHOP.PRODUCT_CATEGORY (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


CREATE TABLE IF NOT EXISTS ESHOP.SALE_PRODUCT (
 ID INT(11) NOT NULL AUTO_INCREMENT,
  PRODUCT_ID INT(11) NOT NULL,
  SALE_PRICE DECIMAL(10,0) NOT NULL,
  PRIMARY KEY (ID),
  INDEX fk_SALE_PRODUCT_1_idx (PRODUCT_ID ASC),
  CONSTRAINT fk_SALE_PRODUCT_1
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES ESHOP.PRODUCT (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

ALTER TABLE ESHOP.ORDER 
CHANGE COLUMN INVOICE_DATE INVOICE_DATE DATETIME NULL DEFAULT NULL ;

ALTER TABLE ESHOP.PRODUCT 
CHANGE COLUMN IS_IN_SPECIAL_OFFERS IS_IN_SPECIAL_OFFERS VARCHAR(45) NULL DEFAULT 'false' ;

CREATE TABLE ESHOP.ORDER_PRODUCT (
  ID INT NOT NULL AUTO_INCREMENT,
  ORDER_ID INT NULL,
  PRODUCT_ID INT NULL,
  AMMOUNT INT NULL,
  PRIMARY KEY (ID),
  INDEX fk_ORDER_PRODUCT_1_idx (ORDER_ID ASC),
  INDEX fk_ORDER_PRODUCT_2_idx (PRODUCT_ID ASC),
  CONSTRAINT fk_ORDER_PRODUCT_1
    FOREIGN KEY (ORDER_ID)
    REFERENCES ESHOP.ORDER (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ORDER_PRODUCT_2
    FOREIGN KEY (PRODUCT_ID)
    REFERENCES ESHOP.PRODUCT (ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
AUTO_INCREMENT = 1;

ALTER TABLE ESHOP.ORDER_PRODUCT 
DROP FOREIGN KEY fk_ORDER_PRODUCT_1,
DROP FOREIGN KEY fk_ORDER_PRODUCT_2;
ALTER TABLE ESHOP.ORDER_PRODUCT 
CHANGE COLUMN ORDER_ID ORDER_ID INT(11) NOT NULL ,
CHANGE COLUMN PRODUCT_ID PRODUCT_ID INT(11) NOT NULL ;
ALTER TABLE ESHOP.ORDER_PRODUCT 
ADD CONSTRAINT fk_ORDER_PRODUCT_1
  FOREIGN KEY (ORDER_ID)
  REFERENCES ESHOP.ORDER (ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT fk_ORDER_PRODUCT_2
  FOREIGN KEY (PRODUCT_ID)
  REFERENCES ESHOP.PRODUCT (ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

